baseURL = "http://localhost:1313/WEB_LOOS/"
#baseURL = "https://pfloos.github.io/WEB_LOOS/"
canonifyurls  = true
languageCode = "en-us"
DefaultContentLanguage = "en"
theme = "beautifulhugo"
title = "Pierre-Francois Loos' research webpage"
[Params]
  hometitle = "Electronic Structure Theory"
  logo="img/PTEROSOR.jpg"
#  subtitle = ""
[[Params.bigimg]]
  src = "img/group.jpg"
  desc = "PTEROSOR group picture (Oct 2024)"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
 [params.author]
   name = "Pierre-Francois Loos"
   email = "loos@irsamc.ups-tlse.fr"
   github = "pfloos"
   twitter = "Titou_Loos"
#   youtube = "channel/UCPUtUMqEM3K5sYcMJGTd_Bg"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "People"
    url = "people"
    weight = 2

[[menu.main]]
    name = "Research"
    url = "research"
    weight = 3

[[menu.main]]
    name = "Publications"
    url = "publications"
    weight = 4

 [[menu.main]]
     name="Talks"
     url = "talks"
     weight = 5

 [[menu.main]]
     name="Funding"
     url = "funding"
     weight = 6

